[package]
name = "pantera-compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
pantera-parser = { path = "../pantera-parser" }
pantera-ast = { path = "../pantera-ast" }
pantera-heap = {path = "../pantera-heap" }
pantera-std = {path = "../pantera-std" }